language: php

php:
  - 7.1
  - nightly

before_script: composer install

script: vendor/bin/phpunit -c tests --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ $(phpenv version-name) = "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'

