name: "Test"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 03 * * 1' # At 03:00 on Monday.

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies: ["lowest", "highest"]
        php-version:
          - "8.2"
          - "8.3"
        operating-system: ["ubuntu-latest"]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies"
        uses: "actions/cache@v4"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Unit tests"
        run: "vendor/bin/phpunit --exclude-group redis"

      - name: "Coding style"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "vendor/bin/phpcs --report=summary"

      - name: "Static analysis"
        run: "vendor/bin/phpstan --no-progress"
