name: "Test Redis"

on:
  push:
  pull_request:

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies: ["lowest", "highest"]
        php-version:
          - "8.2"
        operating-system: ["ubuntu-latest"]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies"
        uses: "actions/cache@v4"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Start Redis"
        uses: "supercharge/redis-github-action@1.8.0"
        with:
          redis-version: "6"

      - name: "Unit tests"
        run: "REDIS_DSN='redis://127.0.0.1:6379' vendor/bin/phpunit --group redis --fail-on-skipped"
